/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DashBoard: typeof import('./src/views/DashBoard.vue')['default']
    FirstCard: typeof import('./src/views/FirstCard.vue')['default']
    NavBar: typeof import('./src/views/NavBar.vue')['default']
    SecondCard: typeof import('./src/views/SecondCard.vue')['default']
    ThirdCard: typeof import('./src/views/ThirdCard.vue')['default']
  }
}
